# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart Trash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'PopupDialog', '~> 0.6'
  pod 'NVActivityIndicatorView'

  # Pods for Smart Trash

end
